# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in codebase_analyzer.gemspec
gemspec

gem "rake", "~> 13.0"

group :development, :test do

  gem 'rspec-core'
  gem 'rspec-expectations'
  gem 'rspec-mocks'
  gem 'rspec-support'
end